from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Literal

from runic.migrate.introspect import LiveSchema
from runic.migrate.manifest import (
    FulltextIndex,
    MandatoryConstraint,
    RangeIndex,
    SchemaManifest,
    UniqueConstraint,
    VectorIndex,
)

log = logging.getLogger(__name__)

_AUTOGEN_COMMENT = "    # AUTOGENERATED — review before applying; cannot detect renames"


@dataclass
class DiffOp:
    action: Literal["create", "drop"]
    op_call: str
    inverse_call: str


# ---------------------------------------------------------------------------
# Canonical key helpers
# ---------------------------------------------------------------------------


def _range_key(idx: RangeIndex) -> tuple:
    entity = "RELATIONSHIP" if idx.rel else "NODE"
    return ("range", entity, idx.label, idx.prop)


def _fulltext_key(idx: FulltextIndex) -> tuple:
    return ("fulltext", "NODE", idx.label, idx.props)


def _vector_key(idx: VectorIndex) -> tuple:
    return ("vector", "NODE", idx.label, idx.prop)


def _constraint_key(c: UniqueConstraint | MandatoryConstraint) -> tuple:
    kind = "UNIQUE" if isinstance(c, UniqueConstraint) else "MANDATORY"
    return (kind, c.entity, c.label, c.props)


# ---------------------------------------------------------------------------
# op call renderers
# ---------------------------------------------------------------------------


def _range_create(idx: RangeIndex) -> str:
    rel_arg = ", rel=True" if idx.rel else ""
    return f"op.create_range_index({idx.label!r}, {idx.prop!r}{rel_arg})"


def _range_drop(idx: RangeIndex) -> str:
    rel_arg = ", rel=True" if idx.rel else ""
    return f"op.drop_range_index({idx.label!r}, {idx.prop!r}{rel_arg})"


def _fulltext_create(idx: FulltextIndex) -> str:
    props_args = ", ".join(repr(p) for p in idx.props)
    extra: list[str] = []
    if idx.language:
        extra.append(f"language={idx.language!r}")
    if idx.stopwords:
        sw = "[" + ", ".join(repr(w) for w in idx.stopwords) + "]"
        extra.append(f"stopwords={sw}")
    extra_str = (", " + ", ".join(extra)) if extra else ""
    return f"op.create_fulltext_index({idx.label!r}, {props_args}{extra_str})"


def _fulltext_drop(idx: FulltextIndex) -> str:
    props_args = ", ".join(repr(p) for p in idx.props)
    return f"op.drop_fulltext_index({idx.label!r}, {props_args})"


def _vector_create(idx: VectorIndex) -> str:
    return (
        f"op.create_vector_index({idx.label!r}, {idx.prop!r}, "
        f"{idx.dimension}, {idx.similarity!r}, "
        f"m={idx.m}, ef_construction={idx.ef_construction}, ef_runtime={idx.ef_runtime})"
    )


def _vector_drop(idx: VectorIndex) -> str:
    return f"op.drop_vector_index({idx.label!r}, {idx.prop!r})"


def _constraint_create(c: UniqueConstraint | MandatoryConstraint) -> str:
    kind = "UNIQUE" if isinstance(c, UniqueConstraint) else "MANDATORY"
    props_repr = "[" + ", ".join(repr(p) for p in c.props) + "]"
    return f"op.create_constraint({kind!r}, {c.entity!r}, {c.label!r}, {props_repr})"


def _constraint_drop(c: UniqueConstraint | MandatoryConstraint) -> str:
    kind = "UNIQUE" if isinstance(c, UniqueConstraint) else "MANDATORY"
    props_repr = "[" + ", ".join(repr(p) for p in c.props) + "]"
    return f"op.drop_constraint({kind!r}, {c.entity!r}, {c.label!r}, {props_repr})"


# ---------------------------------------------------------------------------
# Diff engine
# ---------------------------------------------------------------------------


def diff_schema(manifest: SchemaManifest, live: LiveSchema) -> list[DiffOp]:
    ops: list[DiffOp] = []

    # Build manifest lookup by canonical key
    manifest_range: dict[tuple, RangeIndex] = {
        _range_key(i): i for i in manifest.range_indexes
    }
    manifest_fulltext: dict[tuple, FulltextIndex] = {
        _fulltext_key(i): i for i in manifest.fulltext_indexes
    }
    manifest_vector: dict[tuple, VectorIndex] = {
        _vector_key(i): i for i in manifest.vector_indexes
    }
    manifest_constraints: dict[tuple, Any] = {
        _constraint_key(c): c for c in manifest.constraints
    }

    live_range: dict[tuple, RangeIndex] = {_range_key(i): i for i in live.range_indexes}
    live_fulltext: dict[tuple, FulltextIndex] = {
        _fulltext_key(i): i for i in live.fulltext_indexes
    }
    live_vector: dict[tuple, VectorIndex] = {
        _vector_key(i): i for i in live.vector_indexes
    }
    live_constraints: dict[tuple, Any] = {
        _constraint_key(c): c for c in live.constraints
    }

    # --- DROP ops (live - manifest) ---
    # Drop order: constraints first (before their backing indexes), then indexes

    # Drop constraints not in manifest
    for key, c in live_constraints.items():
        if key not in manifest_constraints:
            ops.append(
                DiffOp(
                    action="drop",
                    op_call=_constraint_drop(c),
                    inverse_call=_constraint_create(c),
                )
            )

    # Drop indexes not in manifest
    for key, idx in live_range.items():
        if key not in manifest_range:
            ops.append(
                DiffOp(
                    action="drop",
                    op_call=_range_drop(idx),
                    inverse_call=_range_create(idx),
                )
            )
    for key, idx in live_fulltext.items():
        if key not in manifest_fulltext:
            ops.append(
                DiffOp(
                    action="drop",
                    op_call=_fulltext_drop(idx),
                    inverse_call=_fulltext_create(idx),
                )
            )
    for key, idx in live_vector.items():
        if key not in manifest_vector:
            ops.append(
                DiffOp(
                    action="drop",
                    op_call=_vector_drop(idx),
                    inverse_call=_vector_create(idx),
                )
            )

    # --- CREATE ops (manifest - live) ---
    # Create order: indexes first (UNIQUE constraint requires prior range index), then constraints

    for key, idx in manifest_range.items():
        if key not in live_range:
            ops.append(
                DiffOp(
                    action="create",
                    op_call=_range_create(idx),
                    inverse_call=_range_drop(idx),
                )
            )
    for key, idx in manifest_fulltext.items():
        if key not in live_fulltext:
            ops.append(
                DiffOp(
                    action="create",
                    op_call=_fulltext_create(idx),
                    inverse_call=_fulltext_drop(idx),
                )
            )
    for key, idx in manifest_vector.items():
        if key not in live_vector:
            ops.append(
                DiffOp(
                    action="create",
                    op_call=_vector_create(idx),
                    inverse_call=_vector_drop(idx),
                )
            )
    for key, c in manifest_constraints.items():
        if key not in live_constraints:
            ops.append(
                DiffOp(
                    action="create",
                    op_call=_constraint_create(c),
                    inverse_call=_constraint_drop(c),
                )
            )

    log.debug("autogen diff: %d ops", len(ops))
    return ops


# ---------------------------------------------------------------------------
# Body renderers
# ---------------------------------------------------------------------------


def render_upgrade_body(ops: list[DiffOp]) -> str:
    lines = [_AUTOGEN_COMMENT]
    lines.extend(f"    {op.op_call}" for op in ops)
    return "\n".join(lines)


def render_downgrade_body(ops: list[DiffOp]) -> str:
    lines = [_AUTOGEN_COMMENT]
    lines.extend(f"    {op.inverse_call}" for op in reversed(ops))
    return "\n".join(lines)
