"""Unit tests for runic.autogen diff engine and code generator."""

from __future__ import annotations

from runic.autogen import (
    DiffOp,
    diff_schema,
    render_downgrade_body,
    render_upgrade_body,
)
from runic.introspect import LiveSchema
from runic.manifest import (
    FulltextIndex,
    MandatoryConstraint,
    RangeIndex,
    SchemaManifest,
    UniqueConstraint,
    VectorIndex,
)


def _empty_live() -> LiveSchema:
    return LiveSchema(
        range_indexes=[],
        fulltext_indexes=[],
        vector_indexes=[],
        constraints=[],
    )


def _empty_manifest() -> SchemaManifest:
    return SchemaManifest()


def test_diff_empty_when_schemas_match() -> None:
    manifest = SchemaManifest(range_indexes=[RangeIndex("Person", "email")])
    live = LiveSchema(
        range_indexes=[RangeIndex("Person", "email")],
        fulltext_indexes=[],
        vector_indexes=[],
        constraints=[],
    )
    assert diff_schema(manifest, live) == []


def test_diff_creates_missing_range_index() -> None:
    manifest = SchemaManifest(range_indexes=[RangeIndex("Person", "email")])
    live = _empty_live()
    ops = diff_schema(manifest, live)
    assert len(ops) == 1
    assert ops[0].action == "create"
    assert "create_range_index" in ops[0].op_call
    assert "Person" in ops[0].op_call
    assert "email" in ops[0].op_call


def test_diff_drops_extra_index() -> None:
    manifest = _empty_manifest()
    live = LiveSchema(
        range_indexes=[RangeIndex("Person", "email")],
        fulltext_indexes=[],
        vector_indexes=[],
        constraints=[],
    )
    ops = diff_schema(manifest, live)
    assert len(ops) == 1
    assert ops[0].action == "drop"
    assert "drop_range_index" in ops[0].op_call


def test_diff_unique_constraint_ordering() -> None:
    """Create path: index before constraint. Drop path: constraint before index."""
    manifest = SchemaManifest(
        range_indexes=[RangeIndex("User", "id")],
        constraints=[UniqueConstraint("NODE", "User", ["id"])],
    )
    live = _empty_live()
    ops = diff_schema(manifest, live)

    # All ops are "create" since live is empty
    assert all(o.action == "create" for o in ops)

    op_calls = [o.op_call for o in ops]
    range_idx = next(i for i, c in enumerate(op_calls) if "create_range_index" in c)
    constraint_idx = next(i for i, c in enumerate(op_calls) if "create_constraint" in c)
    assert range_idx < constraint_idx, "index must be created before constraint"


def test_diff_drop_ordering_constraint_before_index() -> None:
    """Drop path: constraint emitted before its backing index."""
    live = LiveSchema(
        range_indexes=[RangeIndex("User", "id")],
        fulltext_indexes=[],
        vector_indexes=[],
        constraints=[UniqueConstraint("NODE", "User", ["id"])],
    )
    manifest = _empty_manifest()
    ops = diff_schema(manifest, live)

    assert all(o.action == "drop" for o in ops)
    op_calls = [o.op_call for o in ops]
    constraint_idx = next(i for i, c in enumerate(op_calls) if "drop_constraint" in c)
    range_idx = next(i for i, c in enumerate(op_calls) if "drop_range_index" in c)
    assert constraint_idx < range_idx, "constraint must be dropped before index"


def test_render_upgrade_body_contains_comment() -> None:
    ops = [
        DiffOp(
            action="create",
            op_call='op.create_range_index("X", "y")',
            inverse_call='op.drop_range_index("X", "y")',
        )
    ]
    body = render_upgrade_body(ops)
    assert body.startswith("    # AUTOGENERATED")


def test_render_downgrade_body_is_inverse() -> None:
    ops = [
        DiffOp(
            action="create",
            op_call='op.create_range_index("X", "y")',
            inverse_call='op.drop_range_index("X", "y")',
        )
    ]
    up = render_upgrade_body(ops)
    down = render_downgrade_body(ops)
    assert "create_range_index" in up
    assert "drop_range_index" in down


def test_render_downgrade_reverses_order() -> None:
    ops = [
        DiffOp(
            action="create",
            op_call='op.create_range_index("A", "x")',
            inverse_call='op.drop_range_index("A", "x")',
        ),
        DiffOp(
            action="create",
            op_call='op.create_constraint("UNIQUE", "NODE", "A", ["x"])',
            inverse_call='op.drop_constraint("UNIQUE", "NODE", "A", ["x"])',
        ),
    ]
    down = render_downgrade_body(ops)
    lines = [
        l for l in down.splitlines() if l.strip() and not l.strip().startswith("#")
    ]
    assert "drop_constraint" in lines[0]
    assert "drop_range_index" in lines[1]


def test_diff_vector_index() -> None:
    manifest = SchemaManifest(
        vector_indexes=[VectorIndex("Doc", "embedding", 128, "cosine")]
    )
    live = _empty_live()
    ops = diff_schema(manifest, live)
    assert len(ops) == 1
    assert "create_vector_index" in ops[0].op_call
    assert "128" in ops[0].op_call


def test_diff_fulltext_index() -> None:
    manifest = SchemaManifest(fulltext_indexes=[FulltextIndex("Movie", ["title"])])
    live = _empty_live()
    ops = diff_schema(manifest, live)
    assert len(ops) == 1
    assert "create_fulltext_index" in ops[0].op_call


def test_diff_mandatory_constraint() -> None:
    manifest = SchemaManifest(
        constraints=[MandatoryConstraint("NODE", "Person", ["name"])]
    )
    live = _empty_live()
    ops = diff_schema(manifest, live)
    assert len(ops) == 1
    assert "MANDATORY" in ops[0].op_call
